export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (    
    <html lang="en">
      <body>
        {children}
        <footer className="h-20 shadow">
          <p className="text-center">© 2024 CleanTrack. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
